### ISSUE TITLE
AMD support?

### ISSUE THREAD

**Issue by PTNobel** [amonakov/libgl-switcheroo#5]
Is this only for Nvidia drivers? Does it work with AMD/ATI discreet graphic cards?

**Comment by amonakov** [comment]
This is only for primus, so effectively yes, NVIDIA only.

The reason is: this is useful in a situation when one needs to switch between two libraries that could be used simultaneously (in different applications). With open-source graphics stack there's only one libGL, so nothing to switch, and with Catalyst offloading the implementations are mutually exclusive (the switch requires X server restart).

**Comment by PTNobel** [comment]
Thanks for the information!
